
services:
  mysql:
    image: mysql:8.0
    container_name: pharmacy-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2237111@Kas
      MYSQL_USER: anura
      MYSQL_PASSWORD: anura

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - pharmacy-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - pharmacy-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Two listeners: one for inside Docker, one for your host
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
     
    ports:
      - "9092:9092"
    networks:
      - pharmacy-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      # Talk to Kafka on its INTERNAL listener
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_READONLY: "false"
    ports:
      - "8085:8080"
    networks:
      - pharmacy-net

  #------------- Config & Discovery ---------------

  config-server:
    image: config-server:latest
    container_name: config-server
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILE_ACTIVE=docker
    ports: 
      - "8888:8888"
    networks:
      - pharmacy-net

  discovery-server:
    image: discovery-server:latest
    container_name: discover-server
    depends_on:
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    ports:
      - "8761:8761"
    networks:
      - pharmacy-net

  # ---------------- Gateway -------------------
  gateway-service:
    image: gateway-service:latest
    container_name: gateway-service
    depends_on:
      - discovery-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_PROFILE_ACTIVE=docker
    ports:
      - "8083:8080"
    networks:
      - pharmacy-net
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    depends_on:
      - mysql
      - config-server
      - discovery-server
    environment:
      # - SPRING_CONFIG_LOCATION=classpath:./config/auth-service.yml
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_PROFILE_ACTIVE=docker
    ports:
      - "9001:9001"
    networks:
      - pharmacy-net
      

volumes:
  mysql-data:
networks:
  pharmacy-net:
    driver: bridge