spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://config-server:8888"

# server:
#     port: 8083

# eureka:
#     client:
#         service-url:
#             defaultZone: http://localhost:8761/eureka/
        