spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          

      # routes:
      #   - id: inventory-service
      #     uri: lb://inventory-service
      #     predicates:
      #       - Path=/inventory/**

      #   - id: order-service
      #     uri: lb://order-service
      #     predicates:
      #       - Path=/orders/**

      #   - id: drug-service
      #     uri: lb://drug-service
      #     predicates:
      #       - Path=/drugs/**

      #   - id: auth-service
      #     uri: lb://auth-service
      #     predicates:
      #       - Path=/auth/**


server:
    port: 8083

eureka:
    client:
        service-url:
            defaultZone: http://discovery-server:8761/eureka/
        